---

seed: 42
device: cuda
num_gpus: 1
num_clients: 60
clients_per_round: 15
num_rounds: 500

dataset:
  name: cifar10
  num_classes_per_client: 2
  batch_size: 10
  mash_batch_size: 800 # 833 training points for each client according to config

model:
  _target_: FedMix.models.CustomVGG
  num_classes: 10

strategy:
  _target_: FedMix.strategy.FedMix
  fraction_fit: 0.000001
  fraction_evaluate: 0.0
  min_fit_clients: ${clients_per_round}
  min_evaluate_clients: 0
  min_available_clients: ${clients_per_round}

  mixup_ratio: 0.05
  lr_decay_after_each_round: 0.999

client:
  num_local_epochs: 2
  lr: 0.01
