_target_: fedmix.strategy.FedProxCustom
fraction_fit: 0.000001
fraction_evaluate: 0.0
min_fit_clients: 15
min_evaluate_clients: 0
min_available_clients: 15

lr_decay_after_each_round: 0.999
proximal_mu: 0.1